name: Code coverage

on:
  workflow_call:

jobs:
  coverage:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 20
    steps:
      - name: 'Coveralls Finished'
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
